  cloud:
    aws:
      access-key : update
      secret-key : update
      region:
        static : update
      s3:
        bucket : update

  JWT_SECRET_KEY: update
  spring:
    cache:
      type : redis
    redis:
      host: update
      port: 0000


